<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Category Type_TYPE</name>
   <tag></tag>
   <elementGuidId>495ce464-40a8-4cf5-8780-c4fed77ddec0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TYPE</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name = 'TYPE' and @type = 'text' and @id = 'TYPE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a734914d-022b-4341-bb63-a57a7f56aa26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TYPE</value>
      <webElementGuid>d725bb6c-77df-4fb8-8183-66d75d7bb918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c9c19135-06dd-412c-b040-809c3d268625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TYPE</value>
      <webElementGuid>91ca07dd-ed42-4fed-96b5-e9442a432d47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c1c36318-4675-4e9c-a4a5-3fada0f42b9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TYPE&quot;)</value>
      <webElementGuid>0c21335b-ecbc-429e-90df-3357d2a72f0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TYPE']</value>
      <webElementGuid>f2956fcb-307b-416c-92c0-10d2c5782e94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/input</value>
      <webElementGuid>2dd394c7-77e3-4fe8-9cc0-6bb81cd260d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'TYPE' and @type = 'text' and @id = 'TYPE']</value>
      <webElementGuid>0eec82df-c34d-4e3b-938a-6f4a82dd0742</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
