<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Doc. Reference No_formDocReffNo (1)</name>
   <tag></tag>
   <elementGuidId>af405b34-3f43-48ed-bcc2-e0bd4af2f695</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='formDocReffNo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#formDocReffNo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9b5c3c04-ffad-42a8-84d0-9ee590541277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Document Reference</value>
      <webElementGuid>1a4120e3-8c36-4a9c-a996-bdbb382f760e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>db22d210-1998-469f-96da-a3dd7c03abde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formDocReffNo</value>
      <webElementGuid>5a9cd4bc-d173-436c-b3df-abcc17dcc508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8d0d7159-0b7f-491e-9f5d-812eb82cd78b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1234</value>
      <webElementGuid>bb8aa1fc-0c34-4a1c-86b0-8703e5f4544f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formDocReffNo&quot;)</value>
      <webElementGuid>82b58fa6-79da-4e57-9eb3-443cc7859183</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='formDocReffNo']</value>
      <webElementGuid>58b27c49-49d6-411a-b8f0-79c4807cf994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/section[2]/section/div/div/div/div[2]/form/div/div[4]/div/input</value>
      <webElementGuid>f78c3d3c-6ac4-4d23-8fe1-c24a46bb7278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>ff993718-3077-4c3f-9bf4-fb11818abf7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter Document Reference' and @type = 'text' and @id = 'formDocReffNo']</value>
      <webElementGuid>1ba51bea-61e0-4f52-8244-350191bd2f17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
