<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Doc. Reference_formDocReff</name>
   <tag></tag>
   <elementGuidId>2d27db01-44e2-482b-bb3f-d55d205ba2c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#formDocReff</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='formDocReff']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ca37a4ff-0305-4578-bdb5-cfbdd5c5770a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Document Reference</value>
      <webElementGuid>89962d15-1344-44a6-aca9-bd8c130fefb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1416df11-3d96-4b45-97d0-aba1d7b6bdd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formDocReff</value>
      <webElementGuid>e682aa96-0ace-4d7e-ad2d-65953c4d63a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>aa68bd73-fb5d-4141-be0d-343c8e35a43e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formDocReff&quot;)</value>
      <webElementGuid>d1cfcca9-5d6f-478f-9680-d608988643c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='formDocReff']</value>
      <webElementGuid>8adc1375-baac-4dd7-a7b7-b0e82c7d8a11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/section[2]/div/section/div/div/div/div[2]/form/div/div[3]/div/input</value>
      <webElementGuid>68d4a425-0a23-4ab7-9047-eeb2cb6250a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>91e1de4c-5b29-4e0e-9f14-2345dfe3197e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter Document Reference' and @type = 'text' and @id = 'formDocReff']</value>
      <webElementGuid>81e1d52b-3483-4095-a36b-33e48fe2bda5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
