<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Doc. Reference_formDocReff (1)</name>
   <tag></tag>
   <elementGuidId>cd1ce253-8bd9-4f7a-970e-4b4bbb065bda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='formDocReff']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#formDocReff</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c55135ac-ed87-4ea8-9679-bd4ceace27bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Document Reference</value>
      <webElementGuid>7b4a44be-be24-46f4-858e-726c0c36da9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1b9f070d-9328-46a5-ab67-2b4019c9582f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formDocReff</value>
      <webElementGuid>850ab398-3e7e-40af-91d7-8d1c48fd0817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>830ecd6e-460f-4130-9f11-5ea0e25e0a3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>referensi dokumen</value>
      <webElementGuid>d0a1f4b2-e14a-4147-8479-ebb342fcee0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formDocReff&quot;)</value>
      <webElementGuid>ad2fbdcb-7e4e-4744-843e-d8acd8d23c1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='formDocReff']</value>
      <webElementGuid>b91b8639-d6e9-43fd-8dfd-905cfcbd11dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/section[2]/section/div/div/div/div[2]/form/div/div[3]/div/input</value>
      <webElementGuid>9ef7f6da-ade2-4a89-8f73-805bdf0aebff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>eabd4e84-4c71-403b-bdc3-96fa6e1034e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter Document Reference' and @type = 'text' and @id = 'formDocReff']</value>
      <webElementGuid>86bb628c-fed2-4cfa-8325-f048b318e816</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
