<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Doc. Reference No_formDocReffNo</name>
   <tag></tag>
   <elementGuidId>2f3131ff-5b4d-47ce-80a1-9b11ab8126e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#formDocReffNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='formDocReffNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ad9ef3ac-6c9c-41eb-865a-ea5f230daadf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Document Reference</value>
      <webElementGuid>fa6c91bd-c453-4fb8-8499-bd464c6369ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4afea610-5d0a-4e87-8376-0e2b09fe3bd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formDocReffNo</value>
      <webElementGuid>d6dfd9a6-d0ec-4dbf-921f-208cc51e0cda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>28895da8-3965-47d4-b9e5-52a04029231f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formDocReffNo&quot;)</value>
      <webElementGuid>03283fa5-8ce4-4b47-85db-a530c1d390f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='formDocReffNo']</value>
      <webElementGuid>97a57e79-c612-4f92-bf60-99aae7feb7e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/section[2]/div/section/div/div/div/div[2]/form/div/div[4]/div/input</value>
      <webElementGuid>797831d3-4cfd-4a5b-a972-ac7b716f8234</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>5d84640c-8013-42c5-a428-c717c8d79632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter Document Reference' and @type = 'text' and @id = 'formDocReffNo']</value>
      <webElementGuid>25cada5c-5117-4cf7-bee7-4d7657321aa1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
