<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__NAME</name>
   <tag></tag>
   <elementGuidId>816bd21c-8317-4350-a5a2-115adc1f6001</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NAME</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NAME']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c4c0c0a2-62ce-42d5-820f-b1abe0decff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NAME</value>
      <webElementGuid>6e170b75-dffa-4b42-ba84-4b2646fda732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>05f66b6e-d8d5-41d6-9178-52034c4da134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NAME</value>
      <webElementGuid>4cb46ab0-7558-4e1e-8bff-98fa63c869a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e566ce75-7a3f-4c1b-b202-ba8a78753240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NAME&quot;)</value>
      <webElementGuid>8cfb0181-f5b5-47dd-9a7a-ea151350c70e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NAME']</value>
      <webElementGuid>d56be5d1-03c9-4f8a-bb46-ce3cd66f3e8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>3ff7d18a-b2e5-44c9-9aa5-5fa08d267483</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'NAME' and @type = 'text' and @id = 'NAME']</value>
      <webElementGuid>0b805877-622b-4ce2-905e-6c4a82f165ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
