<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Company_COMPANY</name>
   <tag></tag>
   <elementGuidId>5543649c-fed3-4436-965c-60802b96063b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#COMPANY</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='COMPANY']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>99a775a0-1dfe-465b-8d83-36f03255c233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>COMPANY</value>
      <webElementGuid>f2611c41-2c94-424f-8f01-8959f9a136e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c7845c19-39f1-4003-8f4f-2f3fb611d311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>COMPANY</value>
      <webElementGuid>39f0ee9d-eba5-4f29-b15f-1f592d124842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b613d47c-83f3-4be8-9235-766bffad74ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;COMPANY&quot;)</value>
      <webElementGuid>035fab19-8a3c-4cf2-891a-c161c557a79f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='COMPANY']</value>
      <webElementGuid>b3fd6bd6-a100-4f9e-8fa6-3421dd7c0627</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/input</value>
      <webElementGuid>7bafd2c2-33fd-480f-a68b-d9c1a1ad1859</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'COMPANY' and @type = 'text' and @id = 'COMPANY']</value>
      <webElementGuid>7ad66fd4-331c-48f0-9fd0-a9435412c351</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
