<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Human Capital Management Internal - Perusahaan</name>
   <tag></tag>
   <elementGuidId>3d218b72-ea69-4943-9fe9-99241c5e16aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'Human Capital Management Internal - Perusahaan' or . = 'Human Capital Management Internal - Perusahaan')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-3-option-4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>01a7d8f7-6f59-4540-a07d-6e578b01cad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-d7l1ni-option</value>
      <webElementGuid>580f65c4-0e29-4f54-815d-c424d5a9b8cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>906b7648-6eae-45c5-b32a-6fecbc239eb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-3-option-4</value>
      <webElementGuid>b0bcdc98-9524-490e-9f2b-1bba633b0f1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>bc2b5a92-d222-4c15-8f28-3094b48b0f62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>c3363852-8b9c-4773-882e-382a4f736487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b1c33409-7fc8-40ff-b5f0-5653c98758dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Human Capital Management Internal - Perusahaan</value>
      <webElementGuid>806aa415-1c6b-4544-bcb1-5d795f8fe0c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-3-option-4&quot;)</value>
      <webElementGuid>f2e50c6d-22e9-4929-8fb4-e1758c157c60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-3-option-4']</value>
      <webElementGuid>9f3acee0-5892-4e5c-856b-648545807fad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-3-listbox']/div[5]</value>
      <webElementGuid>d74fe6dd-6384-47a1-996a-d86d5ac9e9bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sasaka Teknik - Perusahaan'])[1]/following::div[1]</value>
      <webElementGuid>66f6f4b7-e896-49da-ac28-b7af912457d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kreatif Digital Solution - Perusahaan'])[1]/following::div[2]</value>
      <webElementGuid>176c75c3-d4eb-40d9-a2d6-00f46a2868f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment System Internal - Perusahaan'])[1]/preceding::div[1]</value>
      <webElementGuid>8b765257-b461-4815-b433-dbd446b83e0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Development Internal - Perusahaan'])[1]/preceding::div[2]</value>
      <webElementGuid>f8ccc2c9-3e6c-4c55-b787-4bf0a73a745e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Human Capital Management Internal - Perusahaan']/parent::*</value>
      <webElementGuid>ccb707b5-ee87-4b40-b05c-af724cc0a79b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[5]</value>
      <webElementGuid>a5c846ee-76ee-499e-ab87-ffbd4f5a24fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-3-option-4' and (text() = 'Human Capital Management Internal - Perusahaan' or . = 'Human Capital Management Internal - Perusahaan')]</value>
      <webElementGuid>e71be72d-ce48-41b7-a0c5-5244b22e5138</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
