<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Surya Dwi Saputra - Karyawan</name>
   <tag></tag>
   <elementGuidId>9e1ba0f7-801f-4487-95b8-fd7a4f933e37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'Surya Dwi Saputra - Karyawan' or . = 'Surya Dwi Saputra - Karyawan')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-2-option-5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cd7d5e2d-1ad6-4ff7-ba55-4c763cb5220a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-d7l1ni-option</value>
      <webElementGuid>00f88c51-8136-4d11-92f9-34ce12ee9aad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2096f58b-edb3-4cb6-9562-57d65409ae84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-2-option-5</value>
      <webElementGuid>fd12209a-32c7-47ff-a961-de1016a6cae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>0c9f3deb-6e33-4847-9bc9-4f3765046bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>6461d0e3-311a-4f5b-827b-4947ee50b717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7cb5c207-ab98-4911-aa38-8f4cfa88bea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Surya Dwi Saputra - Karyawan</value>
      <webElementGuid>34e4b7c0-3b53-4d6f-a46f-9dcda6d9a781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-2-option-5&quot;)</value>
      <webElementGuid>36c05319-a47e-4552-985d-adf05920d4b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-2-option-5']</value>
      <webElementGuid>1b8d91d3-3dd1-4715-9f27-82a3f15e6d7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-2-listbox']/div[6]</value>
      <webElementGuid>82ae2c98-1aca-47a4-b06d-78bfe6a88d9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ishmael Yudhistira - Karyawan'])[1]/following::div[1]</value>
      <webElementGuid>91d86f57-5fda-4aaa-b0c9-91be4de63174</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agung Hermawan - TOP LEADER SAWANGAN'])[1]/following::div[2]</value>
      <webElementGuid>b46743d6-bd92-4fcb-9b6c-8dfa0ecb628c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contract Duration'])[2]/preceding::div[1]</value>
      <webElementGuid>b684259e-4c8d-4556-bfa4-45828b9104e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Order Number'])[2]/preceding::div[3]</value>
      <webElementGuid>1c92fb6f-ab33-42f1-ad3a-f01064d7b446</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Surya Dwi Saputra - Karyawan']/parent::*</value>
      <webElementGuid>a191f085-3c51-40a3-898d-749788625a71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[6]</value>
      <webElementGuid>854352f0-c9a0-4521-9aef-f84a5ec6fdb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-2-option-5' and (text() = 'Surya Dwi Saputra - Karyawan' or . = 'Surya Dwi Saputra - Karyawan')]</value>
      <webElementGuid>611142d1-2485-4546-b920-f95faa6d3eb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
