<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contract Date_CONTRACT_DATE</name>
   <tag></tag>
   <elementGuidId>e0a9caa6-c724-4302-90cc-c2e1affc5bd3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CONTRACT_DATE']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CONTRACT_DATE</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>543a13bb-9279-45c2-8ab1-75343f269c3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b3959215-f55c-433d-8fdc-0f1478b32f4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CONTRACT_DATE</value>
      <webElementGuid>2f3e4ace-c9df-4d73-b2a1-c25e222a46d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CONTRACT_DATE</value>
      <webElementGuid>ce9eef2a-a1ed-4195-9adc-8dd38205db8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9b290add-4341-41b1-a4ed-3b12d3ee32c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CONTRACT_DATE&quot;)</value>
      <webElementGuid>3fbe92f4-b799-463c-82e2-efddfe7ba184</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CONTRACT_DATE']</value>
      <webElementGuid>1c4a4f52-df45-436a-81a0-77503da18e28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/div/input</value>
      <webElementGuid>1bf76c28-dc28-4013-ad6c-21e60af7c74c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'CONTRACT_DATE' and @name = 'CONTRACT_DATE']</value>
      <webElementGuid>d5591630-67a4-4138-b5fc-2c30f88ccc29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
