<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contract Number_CONTRACT_NUMBER</name>
   <tag></tag>
   <elementGuidId>cf1eaf6c-4426-41e2-8525-73d66abf5db4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CONTRACT_NUMBER']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CONTRACT_NUMBER</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aad7c253-4a33-4d20-b12f-b3e9931cc82c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CONTRACT_NUMBER</value>
      <webElementGuid>a94085ba-ab57-4e5e-90d8-685f95b27968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ffce0b2c-934c-4be7-aa09-fdc2ea0cddc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CONTRACT_NUMBER</value>
      <webElementGuid>ec36ed7e-9daf-4d47-b7fa-a19a40106c81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0f119c1d-dbf1-4e90-8099-aa7a6b4760a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CONTRACT_NUMBER&quot;)</value>
      <webElementGuid>d092a740-21f6-4ec4-8bf7-acf9795b28b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>BSPD</value>
      <webElementGuid>fb452cd4-cf8f-440d-8454-985eb1656a5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CONTRACT_NUMBER']</value>
      <webElementGuid>29e3b36b-9544-42bd-aafc-3c0c124786d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/input</value>
      <webElementGuid>d478ed48-ecbf-4e31-acfc-39471f057597</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'CONTRACT_NUMBER' and @type = 'text' and @id = 'CONTRACT_NUMBER']</value>
      <webElementGuid>4fc42c60-3826-4aea-9679-2a1cfdd6ca73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
