<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Work Order Number_WORK_ORDER_NUMBER</name>
   <tag></tag>
   <elementGuidId>ac60295a-83cb-4b97-bc26-c0706628ad62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='WORK_ORDER_NUMBER']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#WORK_ORDER_NUMBER</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>56d1f208-aafb-4713-a644-3524083951f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>WORK_ORDER_NUMBER</value>
      <webElementGuid>5da2b1ff-b8de-4202-bc9f-21adcfe13482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>78d43fc9-d80b-40cf-81c2-e9a0a63a1239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>WORK_ORDER_NUMBER</value>
      <webElementGuid>548593a3-774e-4493-83f8-b398e29cdd15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>db63fb9c-89c5-4bb4-a976-e52a9ea5e196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;WORK_ORDER_NUMBER&quot;)</value>
      <webElementGuid>b2e68e55-d32f-461d-a83a-7e7c6df48a72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='WORK_ORDER_NUMBER']</value>
      <webElementGuid>898c2ad3-d668-4e9b-8955-f4bf35f033cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>8214d3f7-d668-4db4-9c46-d219177404be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'WORK_ORDER_NUMBER' and @type = 'text' and @id = 'WORK_ORDER_NUMBER']</value>
      <webElementGuid>8d5a5b80-936f-44e5-91b6-c6d3d0f91839</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
