<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Description_DESCRIPTION</name>
   <tag></tag>
   <elementGuidId>b0da4dc1-eca5-4d70-b94e-aa9a53cc948b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DESCRIPTION']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DESCRIPTION</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3a31f0e2-12be-478f-8775-e8b0432d544b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DESCRIPTION</value>
      <webElementGuid>405a11d9-b92c-40a7-b8af-8a3774e7bff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>58b64162-2306-4a2e-8875-f5badd3af67a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DESCRIPTION</value>
      <webElementGuid>aaccd089-dff0-4cd0-9010-6f4538f223cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>514adcae-a52b-436e-a742-cbedee3e4a04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DESCRIPTION&quot;)</value>
      <webElementGuid>a5cab518-dabc-46e9-a993-d53ee7c9877f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Project BESPEED</value>
      <webElementGuid>f85480e5-4080-4de6-aacb-92db05bbc0e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DESCRIPTION']</value>
      <webElementGuid>4d47393d-e1e9-40cc-8bc0-1496bb639dde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>9e34edc1-b755-411c-861c-ecd0c64a7cd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'DESCRIPTION' and @type = 'text' and @id = 'DESCRIPTION']</value>
      <webElementGuid>d0249e10-16db-45f5-bc17-f8fefdbedf65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
