<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contract Duration_CONTRACT_DURATION</name>
   <tag></tag>
   <elementGuidId>b4f0b88d-9464-4a9f-8103-bd9b636f64af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CONTRACT_DURATION']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CONTRACT_DURATION</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>259e2e17-f087-4fc4-a9f9-cc8a416a06fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CONTRACT_DURATION</value>
      <webElementGuid>f470b6c3-10aa-4ad7-ae98-12ef1ae925db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>de50be28-a6b3-4628-96f7-fb16a3ecd44f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CONTRACT_DURATION</value>
      <webElementGuid>cd020603-bcfc-4e4d-85e2-06cf170a00da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>93b76300-565e-4bb6-8654-c759a43029e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CONTRACT_DURATION&quot;)</value>
      <webElementGuid>738057b3-7d3b-46a2-8a2a-d21b2019ccf0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CONTRACT_DURATION']</value>
      <webElementGuid>de23a7d3-3f6b-4574-b525-c2d70ce1b0d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div/input</value>
      <webElementGuid>96d3ca83-75c6-4011-a8d9-f77234108993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'CONTRACT_DURATION' and @type = 'text' and @id = 'CONTRACT_DURATION']</value>
      <webElementGuid>fbaae0f6-9a18-4572-baae-719bed1875e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
