<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bank Account_BANK_ACCOUNT</name>
   <tag></tag>
   <elementGuidId>e4c28202-52c2-40b4-b0c2-822c2bdbd1f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BANK_ACCOUNT']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BANK_ACCOUNT</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d5069171-5a2c-4952-8cec-4d62eb9391e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BANK_ACCOUNT</value>
      <webElementGuid>d0cb788c-5e54-4ae1-ad85-809ef9e7ba9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b5335dd1-1372-4958-9f87-6f09828aa3dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BANK_ACCOUNT</value>
      <webElementGuid>d46db348-e6fd-42d0-94c3-44b44cae0a2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ba8ffd86-7d67-4317-b41e-6c1498843592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BANK_ACCOUNT&quot;)</value>
      <webElementGuid>47e81580-9fb2-4f14-9feb-ab7598b47d51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>akun Bank</value>
      <webElementGuid>d0197b76-f02f-4602-91d2-20b0743803ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BANK_ACCOUNT']</value>
      <webElementGuid>af84fcd1-93c1-4376-badb-fa013c049dab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/input</value>
      <webElementGuid>036092f0-8279-484d-aaf7-d7737a1fea27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'BANK_ACCOUNT' and @type = 'text' and @id = 'BANK_ACCOUNT']</value>
      <webElementGuid>cedef24f-1cdf-466d-aa1a-91f4b4d760e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
