<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bank Number Phone_BANK_NUMBER_PHONE</name>
   <tag></tag>
   <elementGuidId>78b335d7-6715-40ee-a701-d0fb696a90ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BANK_NUMBER_PHONE']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BANK_NUMBER_PHONE</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5a04b6df-4603-48f0-8bff-17980e75fd0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BANK_NUMBER_PHONE</value>
      <webElementGuid>fdde6b44-5937-4e8b-bcff-3201a7bd9201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>92f7c5e3-052f-441c-b196-015e6b46e750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BANK_NUMBER_PHONE</value>
      <webElementGuid>608926f1-68a8-46ef-ae50-0402b81870f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>65d47914-4e1a-4cec-92f5-250c9705885e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BANK_NUMBER_PHONE&quot;)</value>
      <webElementGuid>65cb5ba9-2357-43e9-8e6d-1debc9c122bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>545123</value>
      <webElementGuid>005c709d-97dc-4051-b5fe-2e68d861c0bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BANK_NUMBER_PHONE']</value>
      <webElementGuid>f2145830-656e-42b9-af77-c64d5141713a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/input</value>
      <webElementGuid>451e5d64-9b91-4f40-ab1a-94b661db8114</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'BANK_NUMBER_PHONE' and @type = 'text' and @id = 'BANK_NUMBER_PHONE']</value>
      <webElementGuid>b368b5a3-718e-4079-8440-60d063fa2ace</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
