<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contact Person Number_CONTACT_PERSON_NUMBER</name>
   <tag></tag>
   <elementGuidId>31230b0f-a316-4277-be21-a3b6b5d8e68e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CONTACT_PERSON_NUMBER']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CONTACT_PERSON_NUMBER</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>232f5434-5da2-453d-a3de-872cc5844ebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CONTACT_PERSON_NUMBER</value>
      <webElementGuid>adfdd56b-c561-4d23-94b2-10a6d49bca79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7fdcbd22-951f-4efe-b77f-6f7f54a65f43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CONTACT_PERSON_NUMBER</value>
      <webElementGuid>38b95629-14c5-4b08-9cee-5e092d8e2953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2df6a8ae-c8d7-454e-b000-d845d8ae9166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CONTACT_PERSON_NUMBER&quot;)</value>
      <webElementGuid>bdbee4b3-9ddf-4c50-addd-c13c892b92f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>62123321</value>
      <webElementGuid>47cbd8e3-5a15-4c8e-bd8b-e61dcfbca6ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CONTACT_PERSON_NUMBER']</value>
      <webElementGuid>9625dda2-a92a-4c75-9401-08c73ccda669</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/input</value>
      <webElementGuid>5439d8e0-3e85-41f7-aafa-a2da9118517b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'CONTACT_PERSON_NUMBER' and @type = 'text' and @id = 'CONTACT_PERSON_NUMBER']</value>
      <webElementGuid>21568d57-d618-4462-939e-267027faafbe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
