<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bank Address_BANK_ADDRESS</name>
   <tag></tag>
   <elementGuidId>5fc01fe7-b605-4351-8719-87ee15411cd7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BANK_ADDRESS']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BANK_ADDRESS</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f1fa06ab-2c28-4071-a777-cbf67a9cefae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BANK_ADDRESS</value>
      <webElementGuid>d470681c-1732-4d7f-a3f0-2a7210069ead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a77ce54c-91a9-420a-acaa-d60fea2db1ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BANK_ADDRESS</value>
      <webElementGuid>277ec4ea-5573-48a7-baa2-90e01812c0d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1724dae3-57f3-4fdd-8790-567062096fdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BANK_ADDRESS&quot;)</value>
      <webElementGuid>64f7db6c-a985-4d29-bbc2-222a6448abe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>menara bca</value>
      <webElementGuid>840d697a-508b-4939-a27e-05526c050a94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BANK_ADDRESS']</value>
      <webElementGuid>de7bb2db-4e01-4e88-8602-3f01c4dcec62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/input</value>
      <webElementGuid>3b2c14d6-b0c8-4600-a502-afdc21a3c3b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'BANK_ADDRESS' and @type = 'text' and @id = 'BANK_ADDRESS']</value>
      <webElementGuid>15915e44-384e-4c4b-811f-3122287ad104</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
