<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Chart of Account Name_ACCOUNT_COA_NAME</name>
   <tag></tag>
   <elementGuidId>5ecefab1-a3f9-4a54-b25e-baa51f4a8b07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ACCOUNT_COA_NAME']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ACCOUNT_COA_NAME</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e41f980e-bab6-4dcc-8548-47f847b085a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ACCOUNT_COA_NAME</value>
      <webElementGuid>0f888d74-1905-4716-8e30-06138ba4cb67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>50d9a8ca-f622-4c2a-b09d-c7a13fb240c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ACCOUNT_COA_NAME</value>
      <webElementGuid>20b8e6cc-c579-4a29-87f5-18d0a5280814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>98e0913e-4a71-4aec-b6ec-09e81aab3fa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ACCOUNT_COA_NAME&quot;)</value>
      <webElementGuid>7e487a87-5d32-4dce-ac16-48db44d41040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>kodok</value>
      <webElementGuid>e68f8c0c-3d70-4655-9ef7-4cf6dfd14d4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ACCOUNT_COA_NAME']</value>
      <webElementGuid>b647a01a-f9fc-45e3-a14d-22a154940601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>57978393-31c9-43f9-9bc7-d95256bed35e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ACCOUNT_COA_NAME' and @type = 'text' and @id = 'ACCOUNT_COA_NAME']</value>
      <webElementGuid>7507d888-08fc-45ae-8cea-fc248df0b9ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
