<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Description_DESCRIPTION</name>
   <tag></tag>
   <elementGuidId>d58a2079-337c-4cc0-8d11-95c8bc24b174</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DESCRIPTION']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DESCRIPTION</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a305a00b-ff0a-4760-a583-2323b6a895d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DESCRIPTION</value>
      <webElementGuid>1d1ec7a3-397b-4de5-b7a3-94620a41feeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>58c02293-e8b0-4729-befe-6d786d887d54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DESCRIPTION</value>
      <webElementGuid>fc22a578-9b8d-4208-8a54-a458d2d0171b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>92c38da5-efe9-4f94-89da-4728d546e723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DESCRIPTION&quot;)</value>
      <webElementGuid>9ab4da53-fd25-4bd8-9bf1-7b79f7692745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>deskripsi</value>
      <webElementGuid>0848c746-09e0-475c-9223-b3b29c5ca4d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DESCRIPTION']</value>
      <webElementGuid>38e3f3d9-d86e-4282-9765-1bb9b1324110</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div/input</value>
      <webElementGuid>22acab4b-418c-4488-98f8-c52e8079279c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'DESCRIPTION' and @type = 'text' and @id = 'DESCRIPTION']</value>
      <webElementGuid>6c15819c-f86d-47e9-9545-ac93d3269f78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
