<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tax Account Name_TAX_ACCOUNT_NAME</name>
   <tag></tag>
   <elementGuidId>1b24dede-58bf-433f-bf71-48658e8c624d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TAX_ACCOUNT_NAME']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#TAX_ACCOUNT_NAME</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e77246bf-fb55-4285-844c-13dfa7dce5de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TAX_ACCOUNT_NAME</value>
      <webElementGuid>cdaab8a8-189f-4e98-bccd-f26bbccb59d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>de06897e-3a44-4639-b754-0cc4cbfea534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TAX_ACCOUNT_NAME</value>
      <webElementGuid>1f4ddbc0-7a14-4557-b743-d1e049154417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8889b636-6ac5-4cb7-b486-b81b1e666cf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TAX_ACCOUNT_NAME&quot;)</value>
      <webElementGuid>7f38a9d4-8df3-4976-aa56-9d074b7e8c1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Pajak 2%</value>
      <webElementGuid>28967e88-8016-45c5-9477-693f00aa5e7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TAX_ACCOUNT_NAME']</value>
      <webElementGuid>093fc0f5-2fc9-4d92-a876-1281e969635a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>317fd7c2-6053-413b-9d6c-0cfca18ee9d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'TAX_ACCOUNT_NAME' and @type = 'text' and @id = 'TAX_ACCOUNT_NAME']</value>
      <webElementGuid>ad5e5868-d2fd-4c38-87ff-6e535c26817d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
