<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Buy Rate_BUY_RATE (1)</name>
   <tag></tag>
   <elementGuidId>f6403e8d-9b28-4052-8685-8a0415f45b4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BUY_RATE']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BUY_RATE</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8da33924-3d88-4b0c-b0cd-663349e49753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BUY_RATE</value>
      <webElementGuid>eb38b16b-ae73-48df-9f44-0d768f9b2447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>104b7068-da24-4c81-b37d-c44fd0365025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BUY_RATE</value>
      <webElementGuid>71693c22-7f2c-4fba-b8c4-f40a0654ea17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5adf87b9-6ee8-4339-9a5a-42416e71707c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>15000</value>
      <webElementGuid>37683203-b17e-4b61-bdf6-57a3f440dcab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BUY_RATE&quot;)</value>
      <webElementGuid>2c8d49d6-6e17-4953-89f2-9c3fa4d9c004</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BUY_RATE']</value>
      <webElementGuid>e8bffd89-8816-4526-a64b-1e78c9f01489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/input</value>
      <webElementGuid>79811feb-b592-4830-98b1-d9e8c3834459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'BUY_RATE' and @type = 'text' and @id = 'BUY_RATE']</value>
      <webElementGuid>41c2182a-11ed-485b-b1e2-70f8b5491f53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
