<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sell Rate_SELL_RATE (1)</name>
   <tag></tag>
   <elementGuidId>dd338ab7-abea-4cb9-9e5c-3b799350c8e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SELL_RATE']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SELL_RATE</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6586c85c-eef0-49dc-99db-8cc1927dbc83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SELL_RATE</value>
      <webElementGuid>ab3d57e1-284c-4565-81c9-3f5392c17b4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b836de53-1e26-4fa8-ba57-e7c2921292c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SELL_RATE</value>
      <webElementGuid>bf0eface-26b4-4df8-b7f3-ef9613489f37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2f276541-c3d8-474f-8c84-4304520ac2b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>17000</value>
      <webElementGuid>1e956acb-eb5d-4c83-9721-eceda7a5d7ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SELL_RATE&quot;)</value>
      <webElementGuid>5c602bd3-6376-4200-a6c3-1b661dcd8eed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SELL_RATE']</value>
      <webElementGuid>fc2f06a5-a090-4dfc-8542-9d040559c0f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div/input</value>
      <webElementGuid>7d1cd77d-cf24-40bb-a88f-bdfda0a60404</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'SELL_RATE' and @type = 'text' and @id = 'SELL_RATE']</value>
      <webElementGuid>97ecc61a-10ec-4ef9-b9ad-411c1200006d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
