<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sell Rate_SELL_RATE</name>
   <tag></tag>
   <elementGuidId>3edd1039-617d-4d81-b82f-939beff1068a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SELL_RATE</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name = 'SELL_RATE' and @type = 'text' and @id = 'SELL_RATE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c06706e7-f322-4628-814f-af47dd4d63ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SELL_RATE</value>
      <webElementGuid>ecb6ee0d-95de-4dec-88bb-260036ee967e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1c80c56a-6e7e-453f-9ed9-718b536fa22f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SELL_RATE</value>
      <webElementGuid>764ce507-8c46-483f-992f-675cb3d4eab9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f8147ef8-1d32-4843-a7cf-58bb8889a05b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SELL_RATE&quot;)</value>
      <webElementGuid>6a20a93d-5121-4f1b-b24f-e00f130fe2c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SELL_RATE']</value>
      <webElementGuid>b9100dc0-de6a-415b-8c23-753731d9f773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div/input</value>
      <webElementGuid>9bb7144b-cb39-4eea-b48b-47e9360c0aa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'SELL_RATE' and @type = 'text' and @id = 'SELL_RATE']</value>
      <webElementGuid>29eb2f98-17a1-4aef-adf6-dda92484cbaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
