<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Buy Rate_BUY_RATE</name>
   <tag></tag>
   <elementGuidId>e23f1804-fd02-456c-9acc-34b9f6a87755</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BUY_RATE</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name = 'BUY_RATE' and @type = 'text' and @id = 'BUY_RATE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0aa03f20-5f45-4502-9058-6a8164f1df80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BUY_RATE</value>
      <webElementGuid>628aa9b1-f7ae-4572-8c79-044ade2d3bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ae912752-8a6d-4160-a2d8-24965ab55a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BUY_RATE</value>
      <webElementGuid>fa08242f-d3f6-4d0e-90b7-c3054cda91de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c3bf8f4c-e60b-4bfb-bbfe-663bb6d7b0dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BUY_RATE&quot;)</value>
      <webElementGuid>6ea17180-b8c3-416e-b156-1e5f96382d04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BUY_RATE']</value>
      <webElementGuid>c305f32c-aed7-480d-b11a-dc8d2811a42d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/input</value>
      <webElementGuid>d0b45d1c-1cec-442f-9966-175401bbecb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'BUY_RATE' and @type = 'text' and @id = 'BUY_RATE']</value>
      <webElementGuid>ccda5838-ee87-480d-944c-af7378fd0fd8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
