<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date_DATE</name>
   <tag></tag>
   <elementGuidId>4da800a9-a8cc-45ab-a0da-586cf5c3e83b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DATE</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DATE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b79650fb-ab4f-4442-9961-a999d934ce4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e901471b-17d5-43b5-8ab1-0341b14d283e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DATE</value>
      <webElementGuid>ce42c300-2be5-48b3-a2d2-7bd3be3212d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DATE</value>
      <webElementGuid>ff306f23-a77d-4b69-bebe-e7d80151b6b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>97b70107-91ae-40d0-add7-85f8a145229a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DATE&quot;)</value>
      <webElementGuid>430611ab-f66b-4ac7-a98c-8f6fd1a9d874</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DATE']</value>
      <webElementGuid>27914b8a-83c7-4c09-85e2-d143262cc83e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/input</value>
      <webElementGuid>3a5305f4-e9de-4ec4-8b8f-bf024e3d3fbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'DATE' and @name = 'DATE']</value>
      <webElementGuid>642a24c1-f5b5-487a-b216-b2a1c7164a08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
