<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sunday Holiday_SUNDAY_HOLIDAY</name>
   <tag></tag>
   <elementGuidId>c42abde9-548d-4c0b-8a01-ca2e1f5f3cf9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SUNDAY_HOLIDAY']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SUNDAY_HOLIDAY</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>05c016c0-a633-4d07-967c-36a7602eb144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SUNDAY_HOLIDAY</value>
      <webElementGuid>e9ce9f5d-21b5-42d2-b6e6-cb9b299d25c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7c099c94-8d58-4850-924b-7be7ff419358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SUNDAY_HOLIDAY</value>
      <webElementGuid>a733a37f-d092-4417-88f5-5bd13e05ad8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a6fb8572-ad00-4eef-96a1-a6def611d684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SUNDAY_HOLIDAY&quot;)</value>
      <webElementGuid>2e7c37d5-34fa-4da7-a6ed-73f1dddef118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>x</value>
      <webElementGuid>ac070f62-d3fb-4e15-a3d1-5837f2030290</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SUNDAY_HOLIDAY']</value>
      <webElementGuid>b135b7c4-205a-4683-8c9f-c8748f93e648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>ae473d14-48eb-446c-9899-7cecad55ce33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'SUNDAY_HOLIDAY' and @type = 'text' and @id = 'SUNDAY_HOLIDAY']</value>
      <webElementGuid>a65cb3e3-fed5-48e5-8840-c7bfc48e24b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
