<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Saturday Holiday_SATURDAY_HOLIDAY</name>
   <tag></tag>
   <elementGuidId>b5af2142-773f-4884-a1b0-aaafd4ff86bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SATURDAY_HOLIDAY']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SATURDAY_HOLIDAY</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0d3d9fff-4a88-4883-aae6-1a8874d32771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SATURDAY_HOLIDAY</value>
      <webElementGuid>4675e73e-5509-46d4-b804-7b12817eabf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>54f6c755-7d49-4a95-842e-1f0d0ac7e8ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SATURDAY_HOLIDAY</value>
      <webElementGuid>b1d7030b-6e8c-44c3-a0b8-f0b55d6432ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b59e62c7-e0dd-4591-af9b-7e2373efcc2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SATURDAY_HOLIDAY&quot;)</value>
      <webElementGuid>a40f4e0c-75ce-42a0-b603-99e4cedb27f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>x</value>
      <webElementGuid>a64df263-4858-425d-8cf0-081360ad97c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SATURDAY_HOLIDAY']</value>
      <webElementGuid>575980ea-071f-49a0-9201-7af76f75d894</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>a252bb69-a8f5-47e3-a874-f6f0ca61bf8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'SATURDAY_HOLIDAY' and @type = 'text' and @id = 'SATURDAY_HOLIDAY']</value>
      <webElementGuid>57bc53c7-00f1-49f0-a050-981873c76c2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
