<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mobile Phone_MOBILE_PHONE</name>
   <tag></tag>
   <elementGuidId>c13a4913-58b5-42d2-9ed4-c79d6cff0b15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='MOBILE_PHONE']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#MOBILE_PHONE</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fccc39b3-7f26-4294-8659-7452ac4cfb00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MOBILE_PHONE</value>
      <webElementGuid>92685346-674b-4dca-97ab-73df5e8eb001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>45e08ecf-02b1-46d7-b5eb-f731b4198a28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MOBILE_PHONE</value>
      <webElementGuid>67446d89-e63a-414f-a0ee-9b2b98698562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5054c777-7371-49b6-bb77-f55db63b4d77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MOBILE_PHONE&quot;)</value>
      <webElementGuid>b53ec55c-1bba-4f81-af82-11c0355d19a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MOBILE_PHONE']</value>
      <webElementGuid>145b9475-18b6-493b-b17e-00b0fca7bbeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>0712a4a9-d21a-4fe3-9274-757e46e40185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'MOBILE_PHONE' and @type = 'text' and @id = 'MOBILE_PHONE']</value>
      <webElementGuid>49421320-28b8-43a7-b5cf-8d5a14ddab43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
