<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Employee Identification Number ( NIK _d0a946</name>
   <tag></tag>
   <elementGuidId>cdd4bb9b-fdb2-4d78-adb4-acc7dcbdb1f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='EMPLOYEE_IDENTIFICATION_NUMBER']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#EMPLOYEE_IDENTIFICATION_NUMBER</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4b912f90-0676-4412-ba03-9e9aae507c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EMPLOYEE_IDENTIFICATION_NUMBER</value>
      <webElementGuid>b3795c10-7c8f-4975-b505-7b69a2ff342a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c4eb4c47-9e12-48ac-9de7-67a66fa477c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EMPLOYEE_IDENTIFICATION_NUMBER</value>
      <webElementGuid>b2bebf16-f794-4736-b085-2cc80f4c5257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e0514288-89f0-4f82-a1bb-a1d2ea266dbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EMPLOYEE_IDENTIFICATION_NUMBER&quot;)</value>
      <webElementGuid>e9c579d1-c608-4e86-8918-860883994f94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='EMPLOYEE_IDENTIFICATION_NUMBER']</value>
      <webElementGuid>f95497a3-d9b8-4484-a437-a044e7001a04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/input</value>
      <webElementGuid>0bc5476c-3840-4491-a93a-bbca4f02553c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'EMPLOYEE_IDENTIFICATION_NUMBER' and @type = 'text' and @id = 'EMPLOYEE_IDENTIFICATION_NUMBER']</value>
      <webElementGuid>01ac1c2f-fdb8-47a5-9aea-01203e3f44ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
