<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone_PHONE (1)</name>
   <tag></tag>
   <elementGuidId>859ae0a3-2ca1-4b04-b883-5e96d61a6ab6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PHONE']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PHONE</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cc62a873-7d36-4f9d-9771-fac523b0de61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PHONE</value>
      <webElementGuid>569ff55e-1127-4211-9dcd-9d8f8b5b2269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>76b87ecf-99f6-4a75-8a72-dd9b703a41d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PHONE</value>
      <webElementGuid>13d8f3bc-11c6-45ef-b3b2-2f4a217e7dc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4d36119c-d6b1-4b0d-ab13-dadd83ef7455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>82501965576</value>
      <webElementGuid>e0cf3e7e-6a38-490a-910b-df40adad62f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PHONE&quot;)</value>
      <webElementGuid>07554dbf-4dc5-427c-8f4e-75eeb6761c3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PHONE']</value>
      <webElementGuid>360cbaf6-9e61-4f89-9b36-5d0bbf019aee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div/input</value>
      <webElementGuid>482bc0a4-b7d9-42f3-ad3d-e0746a32fc6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'PHONE' and @type = 'text' and @id = 'PHONE']</value>
      <webElementGuid>73f418e9-d754-47c2-bd3a-738691a4148e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
