<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mobile Phone_MOBILE_PHONE (1)</name>
   <tag></tag>
   <elementGuidId>6d94eaee-899c-4a01-9d55-c6eb9df6b50e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='MOBILE_PHONE']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#MOBILE_PHONE</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9dcb686a-7a11-4637-b836-11d2ccb90ecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MOBILE_PHONE</value>
      <webElementGuid>d6a79284-4bc4-48d0-a121-2ad54f4223a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c2207011-5aaa-46f0-be8a-cc89094eb77a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MOBILE_PHONE</value>
      <webElementGuid>c0486e96-5c79-4bdf-9ccc-3e74b2ec087f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>608e19c8-3724-41cb-af71-b1fd9d260b3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>89672335576</value>
      <webElementGuid>09df5217-ee96-474b-b05a-2dd289679c86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MOBILE_PHONE&quot;)</value>
      <webElementGuid>d7bdef82-e096-4617-82e8-daa8d15970ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MOBILE_PHONE']</value>
      <webElementGuid>383c4e35-1ba6-4c35-a99c-643496c8a7be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>a3e085ce-9c5c-42f7-9612-b89f12324738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'MOBILE_PHONE' and @type = 'text' and @id = 'MOBILE_PHONE']</value>
      <webElementGuid>60cc2b90-72d3-4710-a800-d819b8b13244</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
