<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Employee Identification Number ( NIK _d0a946 (1)</name>
   <tag></tag>
   <elementGuidId>15fb8f98-8d26-4ac1-be90-2d7193a317db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='EMPLOYEE_IDENTIFICATION_NUMBER']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#EMPLOYEE_IDENTIFICATION_NUMBER</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6bc64e6b-9221-4ba5-9267-3028b36455ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EMPLOYEE_IDENTIFICATION_NUMBER</value>
      <webElementGuid>827c6670-7731-4c81-918d-38f11888b1b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>762abb93-65fc-4717-9231-4fa721ef76a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EMPLOYEE_IDENTIFICATION_NUMBER</value>
      <webElementGuid>b1a0c3aa-748e-4647-baef-c613e89fdcb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>42836f40-becb-4341-b0c9-7bb1838d9de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2501965576</value>
      <webElementGuid>1603715d-6013-42f0-b220-b98727c9997b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EMPLOYEE_IDENTIFICATION_NUMBER&quot;)</value>
      <webElementGuid>d7b4269a-817d-42b0-ad8a-e3db87d39d94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='EMPLOYEE_IDENTIFICATION_NUMBER']</value>
      <webElementGuid>71d11988-118f-4a67-827f-17d62b969666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/input</value>
      <webElementGuid>b0a21333-0815-4a1c-8375-c1bdc879e506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'EMPLOYEE_IDENTIFICATION_NUMBER' and @type = 'text' and @id = 'EMPLOYEE_IDENTIFICATION_NUMBER']</value>
      <webElementGuid>de4d042b-b859-4dc8-a31c-c74cb9a7c298</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
