<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_End Date_END_DATE</name>
   <tag></tag>
   <elementGuidId>7e47ce46-19b0-46f6-bde1-283c89a5d464</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#END_DATE</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='END_DATE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>10d7f625-f0fa-422e-a47d-e0340b0db5b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>53634d53-11da-42a0-a80a-acb55f1698eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>END_DATE</value>
      <webElementGuid>7c309d5b-5647-4218-a0d7-30eae63a8666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>END_DATE</value>
      <webElementGuid>429ee0df-7e2a-4037-925e-66f9a816e4b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>53598301-cc64-4914-a91f-621478b251ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;END_DATE&quot;)</value>
      <webElementGuid>68d4b14f-9f9f-43c3-88d2-0104340f95d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='END_DATE']</value>
      <webElementGuid>37290ea7-f33a-4a39-8bc1-69b42feec4ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/input</value>
      <webElementGuid>59ca9311-1c00-45ec-a181-3eac8ea8d863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'END_DATE' and @name = 'END_DATE']</value>
      <webElementGuid>aae56504-95bb-48ec-b18b-4053ef7394db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
