<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_End Date_END_DATE (2)</name>
   <tag></tag>
   <elementGuidId>cbdea1f0-2e42-47a2-9b09-b1911256b243</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#END_DATE</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='END_DATE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f42cd1b9-51f6-489d-8621-4f349a623758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>721db38a-7f77-4fd0-903c-3fcf9c643a09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>END_DATE</value>
      <webElementGuid>0f046a03-62ed-4d83-b3f0-9e1768d80946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>END_DATE</value>
      <webElementGuid>6acd2953-a8ad-4b98-a047-f4478842ed8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control react-datepicker-ignore-onclickoutside</value>
      <webElementGuid>c542bc86-5b16-4173-830d-90439ba000fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2026-12-31</value>
      <webElementGuid>dd1f1bac-28e1-4933-9a2a-12cafb68e338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;END_DATE&quot;)</value>
      <webElementGuid>784e82ce-90b7-4356-82fc-70c654ac6a35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='END_DATE']</value>
      <webElementGuid>2c95f068-08fa-4334-9dd4-4cf863da4cec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/input</value>
      <webElementGuid>47d29cca-5490-42db-9e16-b353ed994191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'END_DATE' and @name = 'END_DATE']</value>
      <webElementGuid>f358ee8e-9966-4636-ae8d-2c60a6881358</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
