<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__YEAR (1)</name>
   <tag></tag>
   <elementGuidId>56a09ec6-dbb5-49f8-90ef-234b46d98604</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#YEAR</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='YEAR']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>274f3a62-6400-4832-9212-56ae1150be9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>YEAR</value>
      <webElementGuid>f2ccf95d-0f8e-4525-b7fd-a7c7a8a99f2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ad3c538c-9bd6-468e-80f2-aa394f0b13ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>YEAR</value>
      <webElementGuid>ec518807-1398-4882-b144-a288b6012def</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>679d5715-ebe9-4980-9599-f32f082cf916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;YEAR&quot;)</value>
      <webElementGuid>79c6ff55-31e8-4b57-a40b-93531be05c6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='YEAR']</value>
      <webElementGuid>ef8f91c5-07ab-4644-b735-568fbe8c5925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>12c14a0f-8102-4d03-8a39-925a72fe5414</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'YEAR' and @type = 'text' and @id = 'YEAR']</value>
      <webElementGuid>7dd09854-7ed3-49df-9bdf-4a5fd36ed60e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
