<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Start Date_START_DATE (1)</name>
   <tag></tag>
   <elementGuidId>8dd729e7-2b84-4dd2-a824-0ca2a97f6c0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#START_DATE</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='START_DATE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb073662-0493-4d39-92be-b7d4d7154cc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>41cf7471-3d23-4af6-a8d3-adca534489cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>START_DATE</value>
      <webElementGuid>8aa36234-aac3-41ad-ad23-481f75fc4ac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>START_DATE</value>
      <webElementGuid>c039a084-cc13-411e-9e76-22c244ccbbfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>22977f35-7617-4944-9060-a63aea8699a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;START_DATE&quot;)</value>
      <webElementGuid>5ea926b8-df8f-4734-9045-0c9a8bc03208</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='START_DATE']</value>
      <webElementGuid>a9a3165b-eb55-4150-ac2a-6c665baac079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/input</value>
      <webElementGuid>427c0ee1-a1bc-4da7-b016-06d60b11e6b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'START_DATE' and @name = 'START_DATE']</value>
      <webElementGuid>779d9f10-bde3-44f2-ab31-337a896bccd2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
