<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__YEAR (2)</name>
   <tag></tag>
   <elementGuidId>e0adc939-bee0-42bc-b39c-b9e96f947e84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#YEAR</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='YEAR']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>db572131-8164-4be4-a0f0-81605323e273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>YEAR</value>
      <webElementGuid>12fe07be-47fe-45a5-bc1f-a68b6c6cc1ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fe922779-3011-4199-82b5-042986477f25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>YEAR</value>
      <webElementGuid>e9d59ff6-86ab-4e07-89b2-f8f23f3df3d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>acc05da9-71f2-4d6b-b5d6-6ae691f6b7e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>e0e64a41-e77a-4322-be3c-a1249ac98e5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;YEAR&quot;)</value>
      <webElementGuid>6d748265-0b2c-49ee-b8e5-8d4756141d1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='YEAR']</value>
      <webElementGuid>1e5e0294-aee1-4e70-a2da-55655e888877</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>7ccb3f9c-3497-461c-ab2d-71264af01f3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'YEAR' and @type = 'text' and @id = 'YEAR']</value>
      <webElementGuid>a671e84c-3180-4bb1-8d79-b88f3dfb2263</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
