<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Chart of Account Receivable_css-19bb58m</name>
   <tag></tag>
   <elementGuidId>9df84a26-880f-40e2-98ae-e8a3d774679e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ACCOUNT_RECEIVABLE']/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-t3ipsp-control > div.css-hlgwow > div.css-19bb58m</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c80d0ce1-4b16-468c-a0d4-8031183b7d88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-19bb58m</value>
      <webElementGuid>a96767fd-0a09-4074-b921-df790e37cacf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ACCOUNT_RECEIVABLE&quot;)/div[@class=&quot;css-t3ipsp-control&quot;]/div[@class=&quot;css-hlgwow&quot;]/div[@class=&quot;css-19bb58m&quot;]</value>
      <webElementGuid>9e47e834-427b-4a0b-9feb-0320872c05f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ACCOUNT_RECEIVABLE']/div/div/div[2]</value>
      <webElementGuid>5ae6d48d-c340-42fc-92c9-2033c17a873e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chart of Account Receivable'])[2]/following::div[5]</value>
      <webElementGuid>cc879964-df80-4c47-af48-7233b4ae4df3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chart of Account Payable'])[2]/following::div[14]</value>
      <webElementGuid>e49d5777-9c16-41f6-9106-19c2845d2bb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/preceding::div[53]</value>
      <webElementGuid>302ed653-3dc4-471c-9c83-b0f9bc0b8ed8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div/div/div[2]</value>
      <webElementGuid>e92bd9c0-fa70-402f-aaf9-d8741058a3dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
