<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Chart of Account Payable_css-19bb58m</name>
   <tag></tag>
   <elementGuidId>9b2b4440-ac53-48cf-9881-c29f4db0161e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-19bb58m</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[9]/div/div/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>eb32782c-11a0-4e7d-aaa1-59fb0c89910a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-19bb58m</value>
      <webElementGuid>901ef4a6-f018-4190-811e-6e2533597878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ACCOUNT_PAYABLE&quot;)/div[@class=&quot;css-t3ipsp-control&quot;]/div[@class=&quot;css-hlgwow&quot;]/div[@class=&quot;css-19bb58m&quot;]</value>
      <webElementGuid>ac088f2f-ef28-4a72-ac7f-2061e166283e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ACCOUNT_PAYABLE']/div/div/div[2]</value>
      <webElementGuid>1b88e646-d41c-4012-9a32-7e0b3407c706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chart of Account Payable'])[2]/following::div[5]</value>
      <webElementGuid>30e58113-8078-47d4-aec8-db9778bf73ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Person Email'])[2]/following::div[7]</value>
      <webElementGuid>f07e8207-5282-4379-98c3-80e9c559b68a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chart of Account Receivable'])[2]/preceding::div[53]</value>
      <webElementGuid>caa30cb3-0fe8-4ce3-a771-26ec9aefd0d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div/div/div[2]</value>
      <webElementGuid>ed907835-eda9-4357-8d0e-f2621ca938a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
