<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contact Person Number_CONTACT_PERSON_NUMBER (1)</name>
   <tag></tag>
   <elementGuidId>2d89f57e-d4a3-458d-a2d0-f93740e61381</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CONTACT_PERSON_NUMBER']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CONTACT_PERSON_NUMBER</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ef65410c-e981-4935-8b97-510291f143d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CONTACT_PERSON_NUMBER</value>
      <webElementGuid>30063c77-4db9-4b61-a37f-b3f9b3463159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8efa9e5c-dc54-4ecc-8f6b-e51da34d03a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CONTACT_PERSON_NUMBER</value>
      <webElementGuid>e001b530-75f1-49af-b6f0-3b4bdec2a768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6c75647b-4244-4bfd-ae13-49835b062d83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>54321</value>
      <webElementGuid>20aa3a13-23d3-411c-a4a7-1e04bec43398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CONTACT_PERSON_NUMBER&quot;)</value>
      <webElementGuid>c43d2313-ce52-4c8e-ac8b-61618b99b5bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CONTACT_PERSON_NUMBER']</value>
      <webElementGuid>daf77770-6ed3-4218-9e55-09b6913b3816</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/input</value>
      <webElementGuid>c409748f-a47d-4561-bd78-ca8e63ff872a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'CONTACT_PERSON_NUMBER' and @type = 'text' and @id = 'CONTACT_PERSON_NUMBER']</value>
      <webElementGuid>ada2e677-244b-4fc2-b00a-aa45c806b73c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
