<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Npwp Account_NPWP_ACCOUNT (1)</name>
   <tag></tag>
   <elementGuidId>cde8c80a-20d0-477f-ba6a-4c432651306f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NPWP_ACCOUNT']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NPWP_ACCOUNT</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8f150c02-1efc-47eb-8238-ef5162f856b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NPWP_ACCOUNT</value>
      <webElementGuid>a386e4de-bf0c-4260-9711-9bbbafbb7342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6d4ad6ca-fc48-41f1-a06a-7b7279ee432c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NPWP_ACCOUNT</value>
      <webElementGuid>df12da9d-4c76-45e1-8952-535d13b3e724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>43b7cf53-27bc-464d-b915-ec7d73404ff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>12345</value>
      <webElementGuid>bfcd1ba9-5c35-434e-ab13-5fa89d9cbf46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NPWP_ACCOUNT&quot;)</value>
      <webElementGuid>ef73f248-6cd5-43d5-ad76-6249a8ecbc77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NPWP_ACCOUNT']</value>
      <webElementGuid>cff1f91d-0636-41b5-9b90-231f7795b89c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>116732fa-d3b6-4d62-a110-dc5c77e4c674</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'NPWP_ACCOUNT' and @type = 'text' and @id = 'NPWP_ACCOUNT']</value>
      <webElementGuid>098b0f3d-0dbf-42b1-80fe-26ac5dede423</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
