<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Npwp Address_NPWP_ADDRESS (1)</name>
   <tag></tag>
   <elementGuidId>2f31b7ad-7fc5-4c40-933a-f216076879e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NPWP_ADDRESS']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NPWP_ADDRESS</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>93efe2d1-557d-4ba2-8553-bb1ab4970a6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NPWP_ADDRESS</value>
      <webElementGuid>a9ede2e0-906f-4d9b-a836-5b964c0d62d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5f5722e5-75c1-4740-9326-ab2f76c6801c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NPWP_ADDRESS</value>
      <webElementGuid>87c52e4d-76eb-4d6a-8f24-4f3b1f50668b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f528124d-35d9-49c2-9b4c-de670b3e460c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>jalan jalan</value>
      <webElementGuid>44cbc147-347f-400d-b17a-b0eb9e268d39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NPWP_ADDRESS&quot;)</value>
      <webElementGuid>582e0707-540b-4303-8ac2-e7f237b87bab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NPWP_ADDRESS']</value>
      <webElementGuid>078390b3-31c4-4170-abcf-fa6a04c0e3e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>1db7e785-eead-4486-93f2-544a24a5a3e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'NPWP_ADDRESS' and @type = 'text' and @id = 'NPWP_ADDRESS']</value>
      <webElementGuid>4c552f9f-1237-4197-9043-aef9fea5363b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
