<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Description_DESCRIPTION (1)</name>
   <tag></tag>
   <elementGuidId>41f64a34-353a-406f-8eb4-5416174ff253</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DESCRIPTION']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DESCRIPTION</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e4895b58-c0f6-435e-ace7-5874d9e7effa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DESCRIPTION</value>
      <webElementGuid>dfcfc63a-b517-46c8-b091-0f581b25f97c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d020c985-aabe-4b95-a92d-aceedd3078a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DESCRIPTION</value>
      <webElementGuid>81c0832c-5e48-4c7a-ac29-29087fe96021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>20250b38-c7ca-4e3c-918a-0370be2f6235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>sebuah deskripsi</value>
      <webElementGuid>17348f25-3390-42f3-ade8-25c4040f2589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DESCRIPTION&quot;)</value>
      <webElementGuid>4aa3d025-18e7-4fc8-b703-3480fcdde8ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DESCRIPTION']</value>
      <webElementGuid>0d0deea3-cb0b-41d4-b07c-4652ae6d56a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>94e1b0ae-4231-4f9c-87ed-5f8fa69dd55d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'DESCRIPTION' and @type = 'text' and @id = 'DESCRIPTION']</value>
      <webElementGuid>251499eb-9bd0-494d-beb4-d29c4af7d7fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
