<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Npwp Address_NPWP_ADDRESS</name>
   <tag></tag>
   <elementGuidId>cee1e5de-f41a-4f3c-bd95-d962e287fbbe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NPWP_ADDRESS</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name = 'NPWP_ADDRESS' and @type = 'text' and @id = 'NPWP_ADDRESS']&#xd;
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b209239c-88b0-4916-b0d6-286eab1d0e55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NPWP_ADDRESS</value>
      <webElementGuid>e8a3b764-f3bf-4892-9bd4-46b7a9a711ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dc3c0f01-a5f1-4436-818b-b43c31c62f93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NPWP_ADDRESS</value>
      <webElementGuid>9bdc955b-fd93-421c-b71e-16b61dc7842f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>60d1807f-523a-4137-b34d-b09dc3a4ccdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>f</value>
      <webElementGuid>69a74771-ed79-436a-8022-c9b70f0dfb93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NPWP_ADDRESS&quot;)</value>
      <webElementGuid>67c6175a-1a04-40b8-aa11-346b34e036e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NPWP_ADDRESS']</value>
      <webElementGuid>e5d96b49-63e4-420f-949f-283513ace908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>8fd911fb-a882-4948-8833-c23a5e6dd60a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'NPWP_ADDRESS' and @type = 'text' and @id = 'NPWP_ADDRESS']</value>
      <webElementGuid>edc70ae2-f6e8-40a2-801f-4380824a73d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
