<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Description_DESCRIPTION</name>
   <tag></tag>
   <elementGuidId>60e9856f-708a-48fa-94e6-0052de8dd00c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DESCRIPTION']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DESCRIPTION</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>299215fb-0a5a-489f-9d2a-062f204a99ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DESCRIPTION</value>
      <webElementGuid>d02ffd4d-bebe-41ef-9764-ea01aacbdfe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>85d63043-6645-45a7-9c51-c4f29809a780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DESCRIPTION</value>
      <webElementGuid>d45d4163-b74e-4bfe-ad47-fce6ac6d72d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>446b164a-2c67-4228-ba1f-66e391fccd60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DESCRIPTION&quot;)</value>
      <webElementGuid>87641ab9-cca6-43e5-b4b6-cad24dfa1bd9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DESCRIPTION']</value>
      <webElementGuid>727056a4-0e97-46fc-87e4-16b134d4bb93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>f48cde91-1e9f-4535-bc7b-744d439c4b46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'DESCRIPTION' and @type = 'text' and @id = 'DESCRIPTION']</value>
      <webElementGuid>f37e27a4-c7d3-4f55-a5b6-deffa1761667</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
