<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Npwp Account_NPWP_ACCOUNT</name>
   <tag></tag>
   <elementGuidId>87940562-9f56-4e00-9045-d5bdbfcc66cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NPWP_ACCOUNT']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NPWP_ACCOUNT</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>38f4783a-9347-45e2-9bd0-f46eae289b78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NPWP_ACCOUNT</value>
      <webElementGuid>cf066142-0728-4211-b676-aa3a2c642911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f0603330-a8c4-451c-a320-eb94dff11f96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NPWP_ACCOUNT</value>
      <webElementGuid>25e135e5-6041-4076-a1fe-d5d4f10e47c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>71117350-82ad-4d0c-b966-c1bd2946fc2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NPWP_ACCOUNT&quot;)</value>
      <webElementGuid>67dcf2af-c040-48a2-a00b-5b62d6dea146</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NPWP_ACCOUNT']</value>
      <webElementGuid>89340866-1ccb-4709-93a7-47f63d4283c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>959666d4-456f-44b1-989c-939dfc80101c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'NPWP_ACCOUNT' and @type = 'text' and @id = 'NPWP_ACCOUNT']</value>
      <webElementGuid>f09d0d1c-6395-4b11-af4c-3ed10edb6703</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
