<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contact Person Email_CONTACT_PERSON_EMAIL (1)</name>
   <tag></tag>
   <elementGuidId>35f83659-c6ba-4075-9c06-be191d59ab7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CONTACT_PERSON_EMAIL']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CONTACT_PERSON_EMAIL</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb457402-a66f-421e-8c73-f8df79aaa87f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CONTACT_PERSON_EMAIL</value>
      <webElementGuid>993a8ce7-bf80-4586-b9a4-4db042748a48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1de543bf-7e4d-4a69-a37c-f16344ae46fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CONTACT_PERSON_EMAIL</value>
      <webElementGuid>2e2108d9-5f1c-4ed3-bf87-bd0397b39ff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>11c71532-8df1-48b4-89c6-1121f8c91f8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>orang123@gmail.com</value>
      <webElementGuid>2cab11f3-4d23-4ea7-acb0-523953515246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CONTACT_PERSON_EMAIL&quot;)</value>
      <webElementGuid>6dff9d54-b374-4601-a12c-cb1bc13a010e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CONTACT_PERSON_EMAIL']</value>
      <webElementGuid>50e9c38f-ff3a-487e-8ce0-9ba5eae306a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/input</value>
      <webElementGuid>849fe2ff-288d-4589-839c-d79e4ef71e53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'CONTACT_PERSON_EMAIL' and @type = 'text' and @id = 'CONTACT_PERSON_EMAIL']</value>
      <webElementGuid>bd54c2f3-70e3-4525-b80a-aba617f2e491</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
