<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contact Person Number_CONTACT_PERSON_NUMBER</name>
   <tag></tag>
   <elementGuidId>e0ca0f39-9c20-44d8-8048-cd68303ee3f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CONTACT_PERSON_NUMBER']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CONTACT_PERSON_NUMBER</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9d100a14-421c-406c-a0ef-b53044edadd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CONTACT_PERSON_NUMBER</value>
      <webElementGuid>11877a35-4ebb-4eb4-9520-7a250ddb6ef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>77bd4595-6e57-4785-8efb-556a7dbec7d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CONTACT_PERSON_NUMBER</value>
      <webElementGuid>45ebbe76-73bb-4356-adb1-75beb34911d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2faeb283-f8f4-4eb2-b9fd-2cc513e2659c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CONTACT_PERSON_NUMBER&quot;)</value>
      <webElementGuid>a01a67a0-4db6-45e7-970f-d2b7ccac5bc9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CONTACT_PERSON_NUMBER']</value>
      <webElementGuid>56aaf634-0853-4151-a995-3838ead24264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/input</value>
      <webElementGuid>b8d23978-b3fd-4e92-b4d9-08990eace0b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'CONTACT_PERSON_NUMBER' and @type = 'text' and @id = 'CONTACT_PERSON_NUMBER']</value>
      <webElementGuid>5130d049-3fcd-41a3-afce-fd5596f8eaae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
