<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contact Person Email_CONTACT_PERSON_EMAIL</name>
   <tag></tag>
   <elementGuidId>d3e08478-c405-42bb-b07c-28497fa1c488</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CONTACT_PERSON_EMAIL']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CONTACT_PERSON_EMAIL</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>46089a74-125a-42d6-b744-fdfcb0c9298f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CONTACT_PERSON_EMAIL</value>
      <webElementGuid>225c0336-e5f8-4d83-980e-36ed26132c1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>efdf9606-cdaf-4a65-ba2d-da0621d9c007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CONTACT_PERSON_EMAIL</value>
      <webElementGuid>04f14e86-b2d7-4add-9d00-063d16239a53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>863b972f-fcde-48ee-9881-318517804662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CONTACT_PERSON_EMAIL&quot;)</value>
      <webElementGuid>99cf7016-7632-4cda-93b1-3cde8c6c0d1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CONTACT_PERSON_EMAIL']</value>
      <webElementGuid>8e3cea1b-42e6-4494-bcf1-0d4e4edcd2d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/input</value>
      <webElementGuid>5f7a87f2-082a-4449-9ed2-fea32761cf64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'CONTACT_PERSON_EMAIL' and @type = 'text' and @id = 'CONTACT_PERSON_EMAIL']</value>
      <webElementGuid>a05c8c54-5664-467d-a25d-13c6ee63173d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
