<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Rows per page5103050100 Add New Filter _06d2a6</name>
   <tag></tag>
   <elementGuidId>ce4ae24a-2548-48bd-b53a-02acab1dbf8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/section[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.card-body</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bf0e96a0-897b-48bd-9bc8-ee4241c3a8e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-body</value>
      <webElementGuid>abec34fb-9e5a-442d-b4da-a1156fe2b617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rows per page:5103050100 Add New Filter Customize DownloadDownload XLSDownload CSVAll Data XLSAll Data CSV</value>
      <webElementGuid>b8871d5c-0257-46b3-810e-0723e419ad24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;wrapper&quot;]/div[1]/div[@class=&quot;content-wrapper&quot;]/section[@class=&quot;content&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]</value>
      <webElementGuid>e3e147bb-f1d1-4443-8181-6b882da27b60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/section[2]/div/div</value>
      <webElementGuid>a785e05d-a693-40e8-ad8f-a7ae41d5c777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employee Title'])[3]/following::div[2]</value>
      <webElementGuid>b02c48f7-c457-4c87-a014-39774000be42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[2]/following::div[2]</value>
      <webElementGuid>5bf35c30-6477-458e-b233-9d9137fc69ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/div</value>
      <webElementGuid>33fe0a84-bf5e-49e5-8701-a0e7f683378a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Rows per page:5103050100 Add New Filter Customize DownloadDownload XLSDownload CSVAll Data XLSAll Data CSV' or . = 'Rows per page:5103050100 Add New Filter Customize DownloadDownload XLSDownload CSVAll Data XLSAll Data CSV')]</value>
      <webElementGuid>8c9eec5d-48a2-4e2a-ac8d-0959409b60fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
