<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Approved By_formApprovedBy (1)</name>
   <tag></tag>
   <elementGuidId>c7b71b33-7737-4197-869a-5183edb35297</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='formApprovedBy']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#formApprovedBy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e6a544a9-cc06-4cfe-87e4-407d81b669d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Insert Approved By</value>
      <webElementGuid>a7ebcb84-5335-438b-ac2d-cdfd144770a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bcfa2f67-c14e-46ef-a545-d5bd3a254cee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formApprovedBy</value>
      <webElementGuid>76378b9a-54a8-4649-91a3-fc034d0b286f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2bfe53af-e259-43ee-94ce-95ee133836b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>apruved by ptap</value>
      <webElementGuid>00cd6c92-5b88-455a-9c6b-2133bd45c40f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formApprovedBy&quot;)</value>
      <webElementGuid>792dfd93-2bf1-4eee-9821-eea511cf0e5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='formApprovedBy']</value>
      <webElementGuid>16ae435f-468e-4e96-974b-c009f48a8285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/section[2]/section/div/div/div/div[2]/form/div/div[13]/div/input</value>
      <webElementGuid>e4f77633-a919-4ecc-aeb7-9654666a616e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/input</value>
      <webElementGuid>b95432d5-305b-4c10-a3ee-7fb49c11c59c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Insert Approved By' and @type = 'text' and @id = 'formApprovedBy']</value>
      <webElementGuid>678f94d9-2159-4652-9e9d-862ab2d9b869</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
