<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select Document ReferencePurchase Re_5a0a62 (1)</name>
   <tag></tag>
   <elementGuidId>e7398bae-df05-41f8-9491-1483286e06d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='formDocRef']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#formDocRef</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>dcf55c4b-3640-4af0-ba76-00d40c96ea30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Document Number</value>
      <webElementGuid>4fed088e-1ccb-41af-82ad-d4686bc32093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>88779174-bcaf-4198-ba8a-e0cd9c4d77cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formDocRef</value>
      <webElementGuid>fe4fa814-d12d-4146-831a-10075d2b3adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Document ReferencePurchase RequestInternal MemoCustomer Contract</value>
      <webElementGuid>893843b0-bc08-4c97-a016-6b906547b869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formDocRef&quot;)</value>
      <webElementGuid>11f65aaa-706f-49b8-86db-cfbfdc14bdfd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='formDocRef']</value>
      <webElementGuid>a51827d2-c887-453e-bb96-20e427b30fb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/section[2]/section/div/div/div/div[2]/form/div/div[2]/div/select</value>
      <webElementGuid>f020ba4b-e347-4bb6-b185-775eada3d629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Doc. Reference'])[1]/following::select[1]</value>
      <webElementGuid>b12d76e4-820f-494b-b9b7-ae890e896784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PO Number'])[1]/following::select[1]</value>
      <webElementGuid>64192d62-ed0f-42b7-b113-7c6d5949743f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchase Request Number'])[1]/preceding::select[1]</value>
      <webElementGuid>b45f87e2-49ac-4b87-917c-20f432e715bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PR/2024/00078'])[1]/preceding::select[1]</value>
      <webElementGuid>1f742283-7fee-4834-8b78-922a1a8cdcc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>de4ddf45-568c-4a80-8878-7e0398d398d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@placeholder = 'Enter Document Number' and @id = 'formDocRef' and (text() = 'Select Document ReferencePurchase RequestInternal MemoCustomer Contract' or . = 'Select Document ReferencePurchase RequestInternal MemoCustomer Contract')]</value>
      <webElementGuid>d78da559-e941-4cc3-9aa4-10172a5aa8cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
