<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select Document ReferencePurchase Re_5a0a62</name>
   <tag></tag>
   <elementGuidId>33088a1b-7b66-423f-b545-5f5d91d57f07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='formDocRef']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#formDocRef</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b95c3292-aecf-405c-9115-8d7b34fbefbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Document Number</value>
      <webElementGuid>6319c149-b83c-4f3c-9dc7-16ebf2992a5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>1c082730-d2f7-4ad4-98a5-e34d09a9e2b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formDocRef</value>
      <webElementGuid>0ad09d9f-182b-4fa2-8203-68fd22b700d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Document ReferencePurchase RequestInternal MemoCustomer Contract</value>
      <webElementGuid>25b2a234-95d9-47a5-8717-f23aad88297d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formDocRef&quot;)</value>
      <webElementGuid>3204ffde-84df-4eda-a84a-e65c43cdf27a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='formDocRef']</value>
      <webElementGuid>52503568-9361-4b41-be71-0aa203e7126d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/section[2]/div/section/div/div/div/div[2]/form/div/div[2]/div/select</value>
      <webElementGuid>5bc4ee07-5a90-4fcc-8c43-5b4f4df533e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Doc. Reference'])[1]/following::select[1]</value>
      <webElementGuid>73cd617a-4e25-4abf-9231-cb4e9714c3b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PO Number'])[1]/following::select[1]</value>
      <webElementGuid>5bd5c61d-4cbe-4cf4-a3b9-d19eb15da823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='File Document'])[1]/preceding::select[1]</value>
      <webElementGuid>d65834b8-57f4-4b31-b4e5-f91b089b7c07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer'])[2]/preceding::select[1]</value>
      <webElementGuid>13d3cb11-0cbb-4218-8be8-e1c5f37f8dff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>aad2f440-3b76-4af5-826d-6a2e2766c9b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@placeholder = 'Enter Document Number' and @id = 'formDocRef' and (text() = 'Select Document ReferencePurchase RequestInternal MemoCustomer Contract' or . = 'Select Document ReferencePurchase RequestInternal MemoCustomer Contract')]</value>
      <webElementGuid>570a2815-ddcf-4783-b6ce-d5e6de890f54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
