<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Count_COUNT (1)</name>
   <tag></tag>
   <elementGuidId>8dd4aef0-00d2-4f6f-9579-304f5c8f4900</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#COUNT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='COUNT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>39073b15-9c19-47a8-a55f-0815ed6fc05b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>COUNT</value>
      <webElementGuid>58f63218-e915-42c9-844c-cac1cbf90ac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0dd50247-cff1-45ef-b97e-443e728e40a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>COUNT</value>
      <webElementGuid>15987f2a-4806-47c0-abaf-54688abd488b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>61fc5ee8-f9a3-44e3-8488-b4f421bddefb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>21</value>
      <webElementGuid>02561cf8-9d53-40d0-9856-8229433945de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;COUNT&quot;)</value>
      <webElementGuid>7684c8e3-ccdb-43a5-9aa9-1be78740188a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='COUNT']</value>
      <webElementGuid>2b681f6c-92fb-4510-b27f-be867d2c5a5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>19278c5b-90cc-4f6c-8cba-1275ded5272b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'COUNT' and @type = 'text' and @id = 'COUNT']</value>
      <webElementGuid>1a791c10-7527-4560-b5a1-2ce0bf61fbc3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
