<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Count_COUNT</name>
   <tag></tag>
   <elementGuidId>4aac2127-e314-4731-ae03-45d05c1aade3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#COUNT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='COUNT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>38d477ca-89b6-4cc6-aed6-c8d76c5c9508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>COUNT</value>
      <webElementGuid>45cc80ef-3845-4706-8771-223636aa7dfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>72e46add-0b5d-4bcf-99b5-e2947e87dc99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>COUNT</value>
      <webElementGuid>25360759-b671-48e6-9037-7430c9f59484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>41d8e7c6-7ead-4680-b175-669c49aae827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;COUNT&quot;)</value>
      <webElementGuid>0457d38d-75b0-494c-8b91-b1af647698d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='COUNT']</value>
      <webElementGuid>2de69c23-efbe-442d-a2b2-41e4d0c0514e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>16586d7c-79db-4790-b52f-aaf138a9583d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'COUNT' and @type = 'text' and @id = 'COUNT']</value>
      <webElementGuid>7db5d90d-2411-42ca-9fed-b19a6f9fd850</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
