<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__NAME</name>
   <tag></tag>
   <elementGuidId>b7c66d31-b152-4668-a6c4-9c8366733c34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NAME</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NAME']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>22b26a62-8ea9-4842-896d-bf707bf246ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NAME</value>
      <webElementGuid>a5db2828-10c1-4a90-b1dc-30fc77086705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b6c72fa3-784e-4604-9977-2855fca2405d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NAME</value>
      <webElementGuid>b2d4b9d7-2c4c-4e94-b343-9fae906aa0eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c5a9f02d-3e0f-4c57-8ee2-ad7406b1848f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NAME&quot;)</value>
      <webElementGuid>be5aa4f2-9bbe-422a-9774-29515c393df5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NAME']</value>
      <webElementGuid>eb9f26ba-edf6-49b4-8fec-5efec17d0494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div/input</value>
      <webElementGuid>983e129a-a005-43c0-b3cf-ec4b10180146</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'NAME' and @type = 'text' and @id = 'NAME']</value>
      <webElementGuid>ef66c776-c966-4787-a624-f595249dd06a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
